### ISSUE TITLE
Тип данных, в котором бы хранились значения "правда" и "ложь"

### ISSUE THREAD

**Issue by IsThisLoss** [kornilova-l/Cpp-basics-tutorials#1]
>В C++ нет типа данных, в котором бы хранились значения "правда" и "ложь", поэтому "правдой" считается любое значение, не равное 0, а ложью считается 0.

Это в чистом Си нет такого типа данных, а в C++ есть тип bool, который хранит либо true, либо false.

**Comment by Hashcode-Ankit** [comment]
can you please write it in proper english
